In [1]:
import numpy as np

In [6]:
A = np.array([4, 5, 6])
print(A.shape)
print(A.ndim)

(3,)
1


In [8]:
B = np.array([[21, 25, 54], [12, 25, 5], [21, 2, 54]])
print(B.shape)
print(B.ndim)

(3, 3)
2


In [22]:
C = np.array([[[21, 25, 54], [12, 25, 12], [21, 2, 54], ], [[21, 25, 54], [12, 25, 5], [21, 2, 54]], [[21, 25, 54], [12, 25, 5], [21, 2, 54]]])
print(C.shape)
print(C.ndim)

(3, 3, 3)
3


In [31]:
np.asarray([[77,646], [645, 6556], [645, 6556]]).shape

(3, 2)

In [43]:
np.concatenate((np.array([[47, 898], [45, 89]]), np.array([[47, 898], [45, 89], [45, 89]])), axis=0)

array([[ 47, 898],
       [ 45,  89],
       [ 47, 898],
       [ 45,  89],
       [ 45,  89]])

In [44]:
np.concatenate((np.array([[47, 898], [45, 89]]), np.array([[47, 898], [45, 89], [45, 89]])), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [45]:
np.linspace(0, 10, 100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [57]:
A1 = np.arange(0, 100, 0.5)

In [58]:
A1

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
       27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5,
       33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5, 38. ,
       38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5,
       44. , 44.5, 45. , 45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5, 49. ,
       49.5, 50. , 50.5, 51. , 51.5, 52. , 52.5, 53. , 53.5, 54. , 54.5,
       55. , 55.5, 56. , 56.5, 57. , 57.5, 58. , 58.5, 59. , 59.5, 60. ,
       60.5, 61. , 61.5, 62. , 62.5, 63. , 63.5, 64. , 64.5, 65. , 65.5,
       66. , 66.5, 67. , 67.5, 68. , 68.5, 69. , 69.5, 70. , 70.5, 71. ,
       71.5, 72. , 72.5, 73. , 73.5, 74. , 74.5, 75

In [59]:
A1.shape

(200,)

In [60]:
A1 = A1.reshape(A1.shape[0], 1)

In [61]:
A1.shape

(200, 1)

In [62]:
A1 = A1.ravel()

In [63]:
A1.shape

(200,)

In [66]:
A = np.ones((10, 14))

In [67]:
A

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [68]:
A.shape

(10, 14)

In [70]:
B = np.zeros((14, 74, 87, 54))

In [77]:
B.size == 14*74*87*54

True

In [76]:
def initialization(m, n):

    return 0

4363632

In [28]:
import numpy as np
import unittest

In [48]:
def calculate(input: list):
  if len(input) != 9:
    raise ValueError('List must contain nine numbers.')
  mx = np.array(input).reshape(3, 3)
  calculations = {}
  calculations["mean"] = [
    list(np.mean(mx, axis=0)),
    list(np.mean(mx, axis=1)),
    mx.mean()
  ]
  calculations["variance"] = [
    list(np.var(mx, axis=0)),
    list(np.var(mx, axis=1)),
    mx.var()
  ]
  calculations["standard deviation"] = [
    list(np.std(mx, axis=0)),
    list(np.std(mx, axis=1)),
    mx.std()
  ]
  calculations["max"] = [
    list(np.max(mx, axis=0)),
    list(np.max(mx, axis=1)),
    mx.max()
  ]
  calculations["min"] = [
    list(np.min(mx, axis=0)),
    list(np.min(mx, axis=1)),
    mx.min()
  ]
  calculations["sum"] = [
    list(np.sum(mx, axis=0)),
    list(np.sum(mx, axis=1)),
    mx.sum()
  ]
  return calculations

In [49]:
output = calculate([2,6,2,8,4,0,1,5,7])

In [50]:
output

{'mean': [[3.6666666666666665, 5.0, 3.0],
  [3.3333333333333335, 4.0, 4.333333333333333],
  3.888888888888889],
 'variance': [[9.555555555555557, 0.6666666666666666, 8.666666666666666],
  [3.555555555555556, 10.666666666666666, 6.222222222222221],
  6.987654320987654],
 'standard deviation': [[3.091206165165235,
   0.816496580927726,
   2.943920288775949],
  [1.8856180831641267, 3.265986323710904, 2.494438257849294],
  2.6434171674156266],
 'max': [[8, 6, 7], [6, 8, 7], 8],
 'min': [[1, 4, 0], [2, 0, 1], 0],
 'sum': [[11, 15, 9], [10, 12, 13], 35]}

In [40]:
expected = {'mean': [[3.6666666666666665, 5.0, 3.0], [3.3333333333333335, 4.0, 4.333333333333333], 3.888888888888889], 'variance': [[9.555555555555557, 0.6666666666666666, 8.666666666666666], [3.555555555555556, 10.666666666666666, 6.222222222222221], 6.987654320987654], 'standard deviation': [[3.091206165165235, 0.816496580927726, 2.943920288775949], [1.8856180831641267, 3.265986323710904, 2.494438257849294], 2.6434171674156266], 'max': [[8, 6, 7], [6, 8, 7], 8], 'min': [[1, 4, 0], [2, 0, 1], 0], 'sum': [[11, 15, 9], [10, 12, 13], 35]}

In [51]:
output == expected

True

In [21]:
dis = {'m':[1, 2]}